environment:
  channel: nightly
  host: x86_64-pc-windows-msvc
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-aarch64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu
  - TARGET: 1.6.0-x86_64-pc-windows-gnu
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %host%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%
  - rustc -vV
  - cargo -vV
build_script:
  - cargo build
  - cargo build --features "everything debug impl-default"
test_script:
  - cargo test --features "everything debug impl-default"
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/d3d6703d143c888f0a8a
