environment:
  channel: nightly
  host: x86_64-pc-windows-msvc
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: aarch64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %host%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%
  - rustc -vV
  - cargo -vV
  - rustup target add %TARGET%
build_script:
  - cargo build --target=%TARGET%
  - cargo build --target=%TARGET% --features "everything debug impl-default"
test_script:
  - cargo test --target=%TARGET% --features "everything debug impl-default"
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/d3d6703d143c888f0a8a
